### ISSUE TITLE
Problem using get_mh_kernels with unbiasedestimator

### ISSUE THREAD

**Issue by dennisprangle** [pierrejacob/debiasedmcmc#1]
I get an error `Error in sres1$state : $ operator is invalid for atomic vectors` when I try to run the code below. The fix seems pretty simple and I'll submit it as a pull request...

```r
library(debiasedmcmc)
set.seed(1)
logtarget = function(theta) dnorm(theta, log=TRUE)
Sigma = matrix(0.1)
my_kernels = get_mh_kernels(logtarget, Sigma, 1)
rinit = function() rnorm(1)
chains = coupled_chains(my_kernels$kernel, my_kernels$coupled_kernel, rinit) # Works
ue = unbiasedestimator(my_kernels$kernel, my_kernels$coupled_kernel, rinit) # Fails
```

**Comment by pierrejacob** [comment]
Thanks Dennis, we'll fix this in the next version, which we're actively working on (mostly, it will contain more numerical experiments).

**Comment by pierrejacob** [comment]
these functions have changed considerably in the latest update; see vignette.
